name: sshx

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
             curl -sSf https://sshx.io/get | sh 

      - run: 
             sshx
